---=====================================================
--- STEP 14: PERFORM TDE (Transparent Data Encryption)
---=====================================================

-- Step 1. CREATE MASTER KEY
USE master;
GO

IF NOT EXISTS (SELECT * FROM sys.symmetric_keys WHERE name = '##MS_DatabaseMasterKey##')
BEGIN
    CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'QwErTy12345!@#$%';
END
GO

-- CHECK KEY
SELECT * FROM sys.symmetric_keys


-- STEP 2 - CREATE CERTIFICATE
CREATE CERTIFICATE TDECert WITH SUBJECT = 'TDE Cert for Encryption';

-- CHECK CERT
SELECT * FROM sys.certificates

-- STEP 3 - ENABLING TDE FOR DATABASE
USE APU_SEPL
GO

CREATE DATABASE ENCRYPTION KEY  
   WITH ALGORITHM = AES_128
   ENCRYPTION BY SERVER CERTIFICATE TDECert;
GO

ALTER DATABASE APU_SEPL
SET ENCRYPTION ON;

USE master;
GO

SELECT B.NAME AS [DB NAME], A.ENCRYPTION_STATE_DESC, A.KEY_ALGORITHM, A.ENCRYPTOR_TYPE
FROM SYS.DM_DATABASE_ENCRYPTION_KEYS A
INNER JOIN SYS.DATABASES B ON A.DATABASE_ID = B.DATABASE_ID
WHERE B.NAME = 'APU_SEPL'


-- STEP 4 - BACKUP THIS DATABASE
BACKUP DATABASE APU_SEPL 
TO DISK = 'C:\Temp_DBS\Database_Backup\APU_SEPL.bak'


-- STEP 5 - BACKUP THIS CERT FOR DATABASE
USE MASTER
GO

BACKUP CERTIFICATE TDECert 
TO FILE = N'C:\Temp_DBS\Database_Backup\APU_SEPL.cert'
WITH PRIVATE KEY (
    FILE = N'C:\Temp_DBS\Database_Backup\APU_SEPL.key', 
ENCRYPTION BY PASSWORD = 'QwErTy12345!@#$%'
);
GO

----------------------------------------------------------------------
--TEST IN ANOTHER SERVER/INSTANCE

USE MASTER
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'MyBackUpPassword$$12345'

USE MASTER
GO

Create CERTIFICATE TDECert 
From FILE = N'C:\Temp_DBS\Database_Backup\APU_SEPL.cert'
WITH PRIVATE KEY (
    FILE = N'C:\Temp_DBS\Database_Backup\APU_SEPL.key', 
DECRYPTION BY PASSWORD = 'QwErTy12345!@#$%'
);
GO

RESTORE DATABASE APU_SEPL2 -- CHANGE THIS TO RESTORE THE DB IN THE SAME SERVER
FROM DISK = 'C:\Temp_DBS\Database_Backup\APU_SEPL.bak'
WITH MOVE 'APU_SEPL' TO 'C:\Temp_DBS\Database_Backup\APU_SEPL.mdf',
MOVE 'APU_SEPL_Log' TO 'C:\Temp_DBS\APU_SEPL_Log.ldf'
