
---===================================
--- STEP 04: CREATE ENCRYPTION & VIEW 
---===================================


--USE THE DATABASE
USE APU_SEPL
GO

------------------------------DECRYPTION PURPOSES FOR MEMBER TABLE------------------------------
---- MASTER KEY AND ENCRYPT BY PASSWORD
CREATE MASTER KEY ENCRYPTION BY PASSWORD = '12345'
GO

---- CERTIFICATE WITH SUBJECT
CREATE CERTIFICATE CERT_MEMBER WITH SUBJECT = 'CERT_MEMBER'
GO

CREATE CERTIFICATE CERT_MEMBER_STAFF WITH SUBJECT = 'CERT_MEMBER_STAFF'
GO

---- CREATE SYMMETRIC KEY AND ENCRYPT BY CERT
CREATE SYMMETRIC KEY SIMKEY_MEMBER
WITH ALGORITHM = AES_256  
ENCRYPTION BY CERTIFICATE CERT_MEMBER
GO

CREATE SYMMETRIC KEY SIMKEY_MEMBER_STAFF
WITH ALGORITHM = AES_256  
ENCRYPTION BY CERTIFICATE CERT_MEMBER_STAFF
GO

---- DROP IF NECESSARY
DROP SYMMETRIC KEY SIMKEY_MEMBER
DROP CERTIFICATE CERT_MEMBER

DROP SYMMETRIC KEY SIMKEY_MEMBER_STAFF
DROP CERTIFICATE CERT_MEMBER_STAFF

---==============================
--- STEP 4.1: OWN MEMBER INFO VIEW
---==============================
CREATE OR ALTER VIEW DBO.OWN_MEMBER_INFO_VIEW WITH SCHEMABINDING 
AS
SELECT [MEM_ID], CAST(DECRYPTBYKEY([MEM_NRIC_PN]) AS VARCHAR) AS Decrypted_NRIC_PN,[MEM_NAME], 
CAST(DECRYPTBYKEY([MEM_ADDRESS]) AS VARCHAR) AS Decrypted_ADDRESS,[MEM_PHONE_NO],[MEM_LOG_ID]
FROM [DBO].[MEMBER]
GO

-- TESTING PURPOSE
Execute as User = '50003'

OPEN SYMMETRIC KEY SIMKEY_MEMBER
DECRYPTION BY CERTIFICATE CERT_MEMBER
SELECT * FROM OWN_MEMBER_INFO_VIEW		--EVENTHOUGH OTHER PPL HAVE THE SYMMETRY KEY ACCESS, THEY STILL CANNOT VIEW AS THEY ARE NOT GRANTED
CLOSE SYMMETRIC KEY SIMKEY_MEMBER
REVERT

---===============================================
--- STEP 4.2: ALL MEMBER INFO VIEW (STORE CLERK, MANAGEMENT)
---===============================================
CREATE OR ALTER VIEW DBO.ALL_MEMBER_INFO_VIEW
AS
SELECT [MEM_ID], ENCRYPTBYKEY(KEY_GUID('SIMKEY_MEMBER_STAFF'), [MEM_NRIC_PN]) AS MEM_NRIC_PN, [MEM_NAME], 
ENCRYPTBYKEY(KEY_GUID('SIMKEY_MEMBER_STAFF'), [MEM_ADDRESS]) AS MEM_ADDRESS, [MEM_PHONE_NO],
[MEM_STATUS], [MEM_LOG_ID], [MEM_REGISTER_DATE]
FROM [DBO].[MEMBER]


-- TESTING PURPOSE
Execute as User = 'LI_WEI'
Execute as User = 'YEE'

OPEN SYMMETRIC KEY SIMKEY_MEMBER_STAFF
DECRYPTION BY CERTIFICATE CERT_MEMBER_STAFF
SELECT MEM_ID, MEM_NAME, CAST(DECRYPTBYKEY(MEM_ADDRESS) AS VARCHAR) AS MEM_ADDRESS FROM ALL_MEMBER_INFO_VIEW
CLOSE SYMMETRIC KEY SIMKEY_MEMBER_STAFF

REVERT
SELECT user_name()
