--USE THE DATABASE
USE APU_SEPL
GO

---===================================
--- STEP 06: GRANT CONTROL ON KEYS 
---===================================

---- GRANTING THE KEY AND CERT TO MEMBERS
GRANT CONTROL ON SYMMETRIC KEY::SIMKEY_MEMBER TO MEMBERS
GRANT CONTROL ON CERTIFICATE::CERT_MEMBER TO MEMBERS

GRANT CONTROL ON SYMMETRIC KEY::SIMKEY_MEMBER_STAFF TO STORE_CLERKS
GRANT CONTROL ON CERTIFICATE::CERT_MEMBER_STAFF TO STORE_CLERKS

GRANT CONTROL ON SYMMETRIC KEY::SIMKEY_MEMBER_STAFF TO MANAGEMENT
GRANT CONTROL ON CERTIFICATE::CERT_MEMBER_STAFF TO MANAGEMENT


---===========================================
--- STEP 07: GRANT CONTROL ON DATABASE, TABLES
---===========================================


------------------------------DATABASE LEVEL: APU_SEPL------------------------------
GRANT CONTROL ON DATABASE::APU_SEPL TO DBA --HAVE ALL ACCESS
GO

----TEST ACCESS
Execute as User = 'EVONNE'
CREATE TABLE APU_SEPL.DBO.[TEST1] (TEST INT PRIMARY KEY, TESTING123 INT)
DROP TABLE APU_SEPL.DBO.[TEST1]
REVERT

SELECT user_name()


------------------------------TABLE LEVEL: MEMBER------------------------------
GRANT UPDATE ON APU_SEPL.DBO.[MEMBER] TO MEMBERS	--CANNOT SELECT (ROW BASED SECURITY AT VIEW), INSERT, DELETE MEMBER
GRANT SELECT, INSERT, UPDATE ON APU_SEPL.DBO.[MEMBER] TO STORE_CLERKS
DENY SELECT, INSERT, UPDATE, DELETE ON APU_SEPL.DBO.[MEMBER] TO DBA	--CANNOT SELECT, INSERT, UPDATE, DELETE


----TEST ACCESS
Execute as User = '50004'
--UPDATE MEMBER SET MEM_PHONE_NO = '0111122112' WHERE MEM_NAME = 'Adam Walker'
--INSERT INTO DBO.[MEMBER] (MEM_NAME, MEM_PHONE_NO)
--VALUES ('Mary Shitzuki', '0160099890')
SELECT * FROM MEMBER
REVERT

Execute as User = 'YEE'
UPDATE MEMBER SET MEM_PHONE_NO = '0111122199' WHERE MEM_NAME = 'Adam Walker'
SELECT * FROM MEMBER
REVERT

Execute as User = 'EVONNE'
DELETE MEMBER WHERE MEM_NAME = 'Mary Shitzuki'
SELECT * FROM MEMBER
REVERT

Execute as User = 'LI_WEI'
DELETE MEMBER WHERE MEM_NAME = 'Mary Shitzuki'
SELECT * FROM MEMBER
REVERT

--revoke insert on member to members
SELECT user_name()


------------------------------TABLE LEVEL: TRANSACTION------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON APU_SEPL.DBO.[TRANSACTION] TO MEMBERS
GRANT SELECT ON APU_SEPL.DBO.[TRANSACTION] TO STORE_CLERKS	--CANNOT INSERT, UPDATE, DELETE TRANSACTION
DENY INSERT, UPDATE, DELETE ON APU_SEPL.DBO.[TRANSACTION] TO DBA	--CANNOT INSERT, UPDATE, DELETE TRANSACTION
GRANT SELECT ON APU_SEPL.DBO.[TRANSACTION] TO MANAGEMENT	--CANNOT INSERT, UPDATE, DELETE TRANSACTION

----TEST ACCESS
Execute as User = '50004'
--DELETE [TRANSACTION] WHERE MEM_ID = 50009
--INSERT INTO DBO.[TRANSACTION] (TRANS_DATE, MEM_ID)	
--VALUES (GETDATE(), 50010)
Execute as User = 'YEE'
Execute as User = 'EVONNE'
Execute as User = 'LI_WEI'
SELECT * FROM [TRANSACTION]
REVERT

SELECT user_name()


------------------------------TABLE LEVEL: EQUIPMENT------------------------------
GRANT SELECT ON APU_SEPL.DBO.[EQUIPMENT] TO MEMBERS	--CANNOT INSERT, UPDATE, DELETE EQUIPMENT
GRANT SELECT, INSERT, UPDATE, DELETE ON APU_SEPL.DBO.[EQUIPMENT] TO STORE_CLERKS
DENY INSERT, UPDATE, DELETE ON APU_SEPL.DBO.[EQUIPMENT] TO DBA	--CANNOT INSERT, UPDATE, DELETE EQUIPMENT
GRANT SELECT ON APU_SEPL.DBO.[EQUIPMENT] TO MANAGEMENT	--CANNOT INSERT, UPDATE, DELETE EQUIPMENT

----TEST ACCESS
Execute as User = '50005'
Execute as User = 'YEE'
Execute as User = 'EVONNE'
Execute as User = 'LI_WEI'
INSERT INTO DBO.[EQUIPMENT] (EQ_NAME, EQ_PPU, EQ_QUANTITY, EQ_COUNTRY, CAT_ID)
VALUES ('VOLLEYBALL', 50, 3, 'America', 1)
DELETE DBO.[EQUIPMENT] WHERE EQ_NAME = 'VOLLEYBALL'
SELECT * FROM [EQUIPMENT]
REVERT

SELECT user_name()


------------------------------TABLE LEVEL: CATEGORY------------------------------
GRANT SELECT ON APU_SEPL.DBO.[CATEGORY] TO MEMBERS	--CANNOT INSERT, UPDATE, DELETE CATEGORY
GRANT SELECT, INSERT, UPDATE, DELETE ON APU_SEPL.DBO.[CATEGORY] TO STORE_CLERKS
DENY INSERT, UPDATE, DELETE ON APU_SEPL.DBO.[CATEGORY] TO DBA	--CANNOT INSERT, UPDATE, DELETE EQUIPMENT
GRANT SELECT ON APU_SEPL.DBO.[CATEGORY] TO MANAGEMENT	--CANNOT INSERT, UPDATE, DELETE EQUIPMENT

----TEST ACCESS
Execute as User = '50005'
Execute as User = 'YEE'
Execute as User = 'EVONNE'
Execute as User = 'LI_WEI'
INSERT INTO DBO.[CATEGORY] (CAT_NAME)
VALUES ('Skates')
DELETE DBO.[CATEGORY] WHERE CAT_NAME = 'Skates'
SELECT * FROM [CATEGORY]
REVERT

SELECT user_name()


------------------------------TABLE LEVEL: EQ_TRANS------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON APU_SEPL.DBO.[EQ_TRANS] TO MEMBERS	
GRANT SELECT ON APU_SEPL.DBO.[EQ_TRANS] TO STORE_CLERKS	--CANNOT INSERT, UPDATE, DELETE EQ_TRANS
DENY INSERT, UPDATE, DELETE ON APU_SEPL.DBO.[EQ_TRANS] TO DBA	--CANNOT INSERT, UPDATE, DELETE EQ_TRANS
GRANT SELECT ON APU_SEPL.DBO.[EQ_TRANS] TO MANAGEMENT	--CANNOT INSERT, UPDATE, DELETE EQ_TRANS

----TEST ACCESS
Execute as User = '50005'
Execute as User = 'YEE'
Execute as User = 'EVONNE'
Execute as User = 'LI_WEI'
INSERT INTO DBO.[EQ_TRANS] (TRANS_ID, EQ_ID, TRANS_QUANT_PURCHASED)
VALUES (10006, 1, 2)
DELETE DBO.[EQ_TRANS] WHERE TRANS_ID = 10006
SELECT * FROM [EQ_TRANS]
REVERT

SELECT user_name()



-------------------------------------------------------------------------------------------------

----CHECK THE PERMISSION ACCESS OF SPECIFIC ROLE IN SPECIFIC OBJECT
SELECT
    p.class_desc AS 'Permission_Class',
    p.permission_name AS 'Permission_Name',
    p.state_desc AS 'Permission_State',
    r.name AS 'Role_Name',
    u.name AS 'Grantee_Name',
    o.name AS 'Object_Name'
FROM sys.database_permissions p
JOIN sys.database_principals r ON p.grantee_principal_id = r.principal_id
JOIN sys.database_principals u ON p.grantor_principal_id = u.principal_id
JOIN sys.objects o ON p.major_id = o.object_id
WHERE r.name = 'MEMBERS'
ORDER BY r.name 


