--USE THE DATABASE
USE APU_SEPL
GO

---=====================================
--- STEP 09: INSERT VALUES (ENCRYPTED)
---=====================================

---=====================
--- CREATE MEMBER TABLE
---=====================

----INSERT RECORDS INTO MEMBER TABLE
INSERT INTO DBO.[MEMBER] (MEM_NAME, MEM_PHONE_NO)
VALUES ('Adam Walker', '0170099871'),
('Marie Soon Chin Mae', '0162233456'),
('Joyce Frankins', '0169981239'),
('Yuki Nishitori', '0129022337'),
('Tan Foong Kit', '0186712093')

----UPDATE MEMBER CONFIDENTIAL DATA (NOT APPLICABLE FOR ALL USERS, THIS IS JUST FOR DBO TESTING)
OPEN SYMMETRIC KEY SIMKEY_MEMBER
DECRYPTION BY CERTIFICATE CERT_MEMBER
UPDATE DBO.[MEMBER] SET MEM_NRIC_PN = ENCRYPTBYKEY(KEY_GUID('SIMKEY_MEMBER'), '01234567890'), 
MEM_ADDRESS = ENCRYPTBYKEY(KEY_GUID('SIMKEY_MEMBER'), 'ARIANA APARTMENT 1234') WHERE MEM_ID = '50002'
CLOSE SYMMETRIC KEY SIMKEY_MEMBER

-- CHECK AFTER ENCRYPTED DATA IS UPDATED 
OPEN SYMMETRIC KEY SIMKEY_MEMBER
DECRYPTION BY CERTIFICATE CERT_MEMBER
SELECT MEM_ID, CAST(DECRYPTBYKEY([MEM_NRIC_PN]) AS VARCHAR) AS Decrypted_NRIC_PN, 
MEM_NAME, CAST(DECRYPTBYKEY([MEM_ADDRESS]) AS VARCHAR) AS Decrypted_ADDRESS, 
MEM_PHONE_NO, MEM_STATUS, MEM_LOG_ID, MEM_REGISTER_DATE FROM DBO.[MEMBER]
CLOSE SYMMETRIC KEY SIMKEY_MEMBER

----ASSUME THAT THE REGISTER DATE OF FIRST MEMBER WAS TWO YEARS AGO
UPDATE DBO.[MEMBER]
SET	MEM_REGISTER_DATE = '2021-06-09'
WHERE MEM_ID = 50001;

----SELECT TO VIEW RECORDS IF NECESSARY
SELECT * FROM DBO.[MEMBER]

---=========================
--- CREATE TRANSACTION TABLE
---=========================

----INSERT RECORDS INTO TRANSACTION TABLE
INSERT INTO DBO.[TRANSACTION] (TRANS_DATE, MEM_ID)	
VALUES ('2021-06-10', 50001),
('2021-07-10', 50001),
(GETDATE(), 50003),
(GETDATE(), 50004),
(GETDATE(), 50005)

----SELECT TO VIEW RECORDS IF NECESSARY
SELECT * FROM DBO.[TRANSACTION]

---=========================
--- CREATE CATEGORY TABLE
---=========================

----INSERT RECORDS INTO CATEGORY TABLE
INSERT INTO DBO.[CATEGORY] (CAT_NAME, CAT_DISCOUNT_NAME, CAT_DISCOUNT_VALUE)
VALUES ('Balls', '50% off', 0.5),
('Rackets', '10% off', 0.1),
('Bats', '10% off', 0.1),
('Nets', '20% off', 0.2),
('Goggles', NULL, NULL)

----SELECT TO VIEW RECORDS IF NECESSARY
SELECT * FROM DBO.[CATEGORY]

---=========================
--- CREATE EQUIPMENT TABLE
---=========================

----INSERT RECORDS INTO EQUIPMENT TABLE
INSERT INTO DBO.[EQUIPMENT] (EQ_NAME, EQ_PPU, EQ_QUANTITY, EQ_COUNTRY, CAT_ID)
VALUES ('Basketball', 20, 10, 'India', 1),
('Badminton Racket', 100, 20, 'Malaysia', 2),
('Baseball bat', 150, 30, 'China', 3),
('Tennis net', 50, 40, 'India', 4),
('Baseball', 25, 30, 'China', 1)

----SELECT TO VIEW RECORDS IF NECESSARY
SELECT * FROM DBO.[EQUIPMENT]

---=========================
--- CREATE EQ_TRANS TABLE
---=========================

--INSERT RECORDS INTO EQ_TRANS TABLE
INSERT INTO DBO.[EQ_TRANS] (TRANS_ID, EQ_ID, TRANS_QUANT_PURCHASED)
VALUES (10001, 1, 10),
(10002, 2, 20),
(10003, 3, 10),
(10004, 4, 15),
(10005, 5, 20)


----SELECT TO VIEW RECORDS IF NECESSARY
SELECT * FROM DBO.[EQ_TRANS]